name: Build HTML File

on: push

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Flatten assets
        run: |
          cd docs
          mkdir -p assets
          cp */assets/* assets/
    
      - name: Convert to HTML
        uses: docker://pandoc/core:3.5
        with:
          args: |
            */*.md
            -s 
            --toc --toc-depth=2
            --css style.css
            --embed-resources
            -o result.html
      - name: Upload HTML
        uses: actions/upload-artifact@v4
        with:
          name: result.html
          path: result.html