name: Build HTML File

on: push

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get file list
        id: files_list
        run: |
          echo "files=$(printf '"%s" ' docs/*/*.md)" > $GITHUB_OUTPUT

      - name: Flatten assets
        run: |
          mkdir -p assets
          cp docs/*/assets/* assets/
    
      - name: Convert to HTML
        uses: docker://pandoc/core:3.5
        with:
          args: ${{ steps.files_list.outputs.files }} -s --toc --toc-depth 2 --css docs/style.css --embed-resources -o result.html

      - name: Upload HTML
        uses: actions/upload-artifact@v4
        with:
          name: result.html
          path: result.html